# Generated by Django 3.2.12 on 2022-03-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message_board',
            },
        ),
    ]
