# Generated by Django 3.2.12 on 2022-03-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messageboard',
            table='MessageBoard',
        ),
    ]
